local tmp = assert(vim.env.AGENT_REVIEW_TEST_TMP)
vim.fn.mkdir(tmp, "p")
local function git(...)
  local args = { "git", "-C", tmp }
  vim.list_extend(args, { ... })
  local result = vim.system(args, { text = true }):wait()
  assert(result.code == 0, result.stderr)
end

git("init", "-q")
git("config", "user.email", "test@example.com")
git("config", "user.name", "Test")
local path = tmp .. "/review.lua"
vim.fn.writefile({ "local old_name = 1", "keep" }, path)
git("add", "review.lua")
git("commit", "-qm", "initial")
vim.fn.writefile({ "local new_name = 2", "keep", "added" }, path)
vim.cmd.edit(vim.fn.fnameescape(path))

local diff = require("agent_diff")
diff.setup({ initial_timeout_ms = 100, live_timeout_ms = 50 })
diff.open()
assert(vim.wait(10000, function()
  local session = diff.get_session()
  return session and session.diff_result and #session.diff_result.changes > 0
end, 10), "Agent Diff did not open")

local session = assert(diff.get_session())
assert(session.layout == "inline")
assert(#vim.api.nvim_list_tabpages() == 1)
local working_context = assert(require("agent_review.target").context_for_buffer(session.modified_buf))
assert(working_context.host == "agent_diff")
assert(working_context.side == "working")
assert(working_context.base_revision == "HEAD")
local old_context = assert(require("agent_review.target").context_for_buffer(session.original_buf))
assert(old_context.host == "agent_diff")
assert(old_context.side == "old")
assert(old_context.path == "review.lua")

vim.api.nvim_win_set_cursor(0, { 1, 0 })
local candidates = require("agent_review.agent_diff").old_lines_at_cursor(1)
assert(#candidates > 0)
local annotation = assert(require("agent_review").annotation.add_old({ body = "keep the old name" }))
assert(annotation.target.side == "old")
assert(annotation.host == "agent_diff")
require("agent_review.render").refresh_buffer(session.modified_buf)
local review_ns = vim.api.nvim_create_namespace("agent_review_render")
assert(#vim.api.nvim_buf_get_extmarks(session.modified_buf, review_ns, 0, -1, {}) > 0)

diff.toggle()
assert(session.layout == "side-by-side")
assert(#vim.api.nvim_tabpage_list_wins(0) == 2)
assert(require("agent_review.target").context_for_buffer(session.original_buf).side == "old")
diff.toggle()
assert(session.layout == "inline")
assert(#vim.api.nvim_tabpage_list_wins(0) == 1)
diff.close()
assert(diff.get_session() == nil)

print("PASS agent_diff.lua")
