local file = assert(vim.env.AGENT_REVIEW_TEST_FILE)
vim.cmd("edit " .. vim.fn.fnameescape(file))
require("agent_bridge").setup({})
local review = require("agent_review")

assert(vim.fn.exists(":Agent") == 2 and vim.fn.exists(":AgentReview") == 2)
assert(vim.fn.exists(":AgentBridge") == 0 and vim.fn.exists(":AgentReviewAdd") == 0)

vim.cmd("AgentReview add")
local input_buf = vim.api.nvim_get_current_buf()
assert(vim.bo[input_buf].filetype == "markdown")
assert(require("agent_review.rpc").context().current.file ~= nil)
vim.api.nvim_buf_set_lines(input_buf, 0, -1, false, { "command", "comment" })
vim.api.nvim_feedkeys(vim.keycode("<C-s>"), "xt", false)
assert(vim.wait(1000, function()
  return #review.annotation.list({ all = true }) == 1
end, 10))
assert(review.annotation.list({ all = true })[1].body == "command\ncomment")

vim.cmd("Agent compose file")
local prompt_buf = vim.api.nvim_get_current_buf()
local prompt_win = vim.api.nvim_get_current_win()
assert(vim.bo[prompt_buf].filetype == "markdown")
local prompt_lines = vim.api.nvim_buf_get_lines(prompt_buf, 0, -1, false)
assert(table.concat(prompt_lines, "\n"):find("@", 1, true))
assert(prompt_lines[#prompt_lines] == "", "composer must start after context, not inside it")
local prompt_config = vim.api.nvim_win_get_config(prompt_win)
assert(prompt_config.border and #prompt_config.border > 0 and prompt_config.title and prompt_config.footer)
assert(prompt_config.width >= 48)
vim.api.nvim_feedkeys(vim.keycode("<C-c>"), "xt", false)
vim.wait(100)

local review_completion = vim.fn.getcompletion("AgentReview session ", "cmdline")
assert(vim.tbl_contains(review_completion, "new"))
local agent_completion = vim.fn.getcompletion("Agent compose ", "cmdline")
assert(vim.tbl_contains(agent_completion, "diagnostics"))
