#!/usr/bin/env zsh

F=/usr/share/zsh-antidote/antidote.zsh; [ -f $F ] && . $F
F=~/.antidote/antidote.zsh; [ -f $F ] && . $F

antidote load

[ -z "$COLORFGBG" ] && export COLORFGBG='7;0'

export VISUAL="nvim"
export EDITOR="nvim"
export GIT_EDITOR="nvim"

alias cat="bat"

alias gb="git branch"
alias gbd="git branch -D"

alias gco="git checkout"
alias gcob="git checkout -b"
alias gcod="git checkout develop"
alias gcom="git checkout main"

alias gc="git commit"
alias gci="git commit --allow-empty -m 'ci: bump'"
alias gcm="git commit -m"

alias gcp="git cherry-pick"

alias gl="git pull"
alias gp="git push"

alias lad="lazydocker"
alias lag="lazygit"

alias ls="eza"
alias la="eza -laag --icons"
alias lt="eza -T --icons"

alias ta="tmux a"

alias v="nvim ."
alias vi="nvim"
alias vim="nvim"

alias te="nvim ~/.config/tmux/tmux.conf"
alias ve="nvim ~/.config/nvim"
alias ze="nvim ~/.zshrc"

alias reload="source ~/.zshrc"

alias sail="./vendor/bin/sail"
alias stripe="docker run --network=host --rm -it stripe/stripe-cli"

alias tsd="sudo tailscale down"
alias tsu="sudo tailscale up --accept-dns"

F=~/.private.zsh; [ -f $F ] && . $F
F=~/.greenlight.zsh; [ -f $F ] && . $F
F=~/.vimme.zsh; [ -f $F ] && . $F
F=~/.jabba/jabba.sh; [ -f $F ] && . $F

eval "$(zoxide init zsh)"
eval "$(op completion zsh)"; compdef _op op
type starship_zle-keymap-select >/dev/null || eval "$(starship init zsh)"

function zvm_after_init() {
  eval "$(atuin init zsh)"
}
