#!/usr/bin/env zsh

export BUN_INSTALL="$HOME/.bun"
export VOLTA_HOME="$HOME/.volta"
export COMPOSER_BIN="$HOME/.config/composer/vendor/bin"
export GOPATH="$HOME/go"

path=(
  "$HOME/.local/bin"
  "$HOME/.opencode/bin"
  "$VOLTA_HOME/bin"
  "$BUN_INSTALL/bin"
  "$HOME/.cargo/bin"
  "$HOME/.go/bin"
  "$GOPATH/bin"
  "$COMPOSER_BIN"
  $path
)

typeset -U path PATH
export PATH
