#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SYSTEM="$( uname )"

cd $DIR


FONTS=$DIR/fonts/SourceCodePro

if [ $SYSTEM = "Darwin" ]; then
    LOCAL_FONTS="$HOME/Library/Fonts"
else
    LOCAL_FONTS="$HOME/.fonts"
    mkdir -p "$LOCAL_FONTS"
fi

for FONT in $FONTS/*.otf
do
    cp "$FONT" "$LOCAL_FONTS"
done

if [ $SYSTEM != "Darwin" ]; then
    fc-cache -f -v
fi

git submodule update --recursive --init --quiet

ln -sfn "$DIR/zsh/antigen" "$HOME/.antigen"
ln -sfn "$DIR/base16-shell" "$HOME/.base16-shell"
ln -sf "$DIR/zsh/zshrc" "$HOME/.zshrc"
