#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SYSTEM="$( uname )"

cd $DIR

git submodule update --recursive --init --quiet

$DIR/fonts/install.sh

ln -sfn "$DIR/zsh/antigen" "$HOME/.antigen"
ln -sfn "$DIR/base16-shell" "$HOME/.base16-shell"
ln -sf "$DIR/zsh/zshrc" "$HOME/.zshrc"
ln -sf "$DIR/vimrc" "$HOME/.vimrc"
