promptToReturnFromSubprocess: false

os:
  edit: '~/.local/bin/lazygit-nvim edit "{{filename}}"'
  editAtLine: '~/.local/bin/lazygit-nvim line "{{line}}" "{{filename}}"'
  editAtLineAndWait: '~/.local/bin/lazygit-nvim wait "{{line}}" "{{filename}}"'
  openDirInEditor: '~/.local/bin/lazygit-nvim dir "{{dir}}"'
