local file = assert(vim.env.NATIVE_REVIEW_TEST_FILE)
vim.cmd("edit " .. vim.fn.fnameescape(file))
local annotations = require("native_review").annotations()
assert(#annotations == 1 and annotations[1].session_id)
local sessions = require("native_review.sessions").list(nil, { include_archived = true })
assert(#sessions == 1 and sessions[1].name == "Migrated review")
assert(require("native_review.persistence").save_now())

local document = vim.json.decode(table.concat(vim.fn.readfile(vim.env.NVIM_NATIVE_REVIEW_STATE), "\n"))
assert(document.schemaVersion == 2)
assert(#document.sessions == 1)
assert(document.annotations[1].sessionId == sessions[1].id)
