source $HOME/.antigen/antigen.zsh

# prompt configs
export PROMPT_ON_NEWLINE=true
export ZLE_RPROMPT_INDENT=0

# allow usage of C-q and C-s shortcuts other places
stty -ixon
stty start undef
stty stop undef

antigen use oh-my-zsh

antigen bundle brew
antigen bundle composer
antigen bundle extract
antigen bundle git
antigen bundle git-extras
antigen bundle vagrant
antigen bundle wp-cli
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme jeffhertzler/zsh-themes agnoster

antigen apply

which -s brew >> /dev/null
if [ $? = 0 ]
  then
    export PATH="$(brew --prefix homebrew/php/php56)"/bin:/usr/local/sbin:/usr/local/bin:$PATH
fi

export COMPOSER_DISABLE_XDEBUG_WARN=1
which -s composer >> /dev/null
if [ $? = 0 ]
  then
    export PATH=~/.composer/vendor/bin:$PATH
fi

alias vi=vim
export EDITOR=vim

if type nvim >/dev/null 2>/dev/null; then
  alias vi=nvim
  alias vim=nvim
  export EDITOR=nvim
fi

BASE16_SHELL="$HOME/.base16-shell/base16-eighties.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

alias art='php artisan'
alias vsync='vagrant gatling-rsync-auto local'
alias gfs='git stash -u && git pull && git stash drop'
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias ze="vim ~/.zshrc && reload"
alias ve="vim ~/.vimrc"


export FZF_DEFAULT_COMMAND='(git ls-files && git ls-files -o --exclude-standard || ag -g "") 2> /dev/null'

[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
