source $HOME/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme agnoster

antigen apply

which -s brew >> /dev/null
if [ $? = 0 ]
    then
        export PATH="$(brew --prefix homebrew/php/php55)"/bin:/usr/local/sbin:/usr/local/bin:$PATH
fi
