source $HOME/.antigen/antigen.zsh

# prompt configs
export PROMPT_ON_NEWLINE=true
export ZLE_RPROMPT_INDENT=0
antigen use oh-my-zsh

antigen bundle brew
antigen bundle composer
antigen bundle extract
antigen bundle git
antigen bundle git-extras
antigen bundle vagrant
antigen bundle wp-cli
antigen bundle zsh_reload
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme jeffhertzler/zsh-themes agnoster

antigen apply

which -s brew >> /dev/null
if [ $? = 0 ]
    then
        export PATH="$(brew --prefix homebrew/php/php56)"/bin:/usr/local/sbin:/usr/local/bin:$PATH
fi

export PATH=~/.composer/vendor/bin:$PATH

export EDITOR=vim

alias art='php artisan'
